---
- hosts: after
  name: StartFuckingDocker  
  vars:
    ansible_port: '1834'
 
  tasks:
    - name: Start that bitch up
      shell:
        chdir: /etc/skillcloud-nginx/
        cmd: "docker-compose up"
        
...
