---
- name: Create Users
  hosts: all
  become: true
  vars_files:
    - privvars.yml
 
  tasks:
    - name: User_Webdeveloper
      user:
        name: "{users}"
        password: "{ passwords | password_hash('sha512') }"
        shell: /bin/bash
        state: present
      loop:
        - Webdeveloper
        - Devopsengineer
...
